<div class="container">

  <section>
    <div class="page-header">
      <h1>Subject Areas</h1>
    </div>

    <div class="row">
      <div class="span6">
        <ul id="subjects_list">
          <li><a>Subject Area</a></li>
        </ul>
      </div>

      <div class="span10" id="subject_area">
        <h3>Choose a Subject on the left to see more</h3>

      </div>

    </div>
  </section>
</div>
