<div class="container">

  <section>
    <div class="page-header">
      <h1>Universities</h1>
    </div>

    <div class="row">
      <div class="span6">
        <ul id="universities_list">
        </ul>
      </div>

      <div class="span10" id="university_info">
        <h3>Choose a University on the left to see more</h3>

        <div id="universities_league">
        </div>
      </div>
    </div>
  </section>
</div>
